### ISSUE TITLE
Feature-request: add an extension field in trigger to render the name of diagnosis

### ISSUE THREAD

**Issue by hj24** [kubediag/kubediag#119]
考虑后面加个扩展字段让用户填一个符合要求的 string，trigger 创建的时候用这个 string 去渲染 diagnosis 的 name，比如：
有形如 pod memory usage 的报警，trigger 里面扩展个字段，用户可以填成 pod_memory_usage，这样生成的 diagnosis 就叫prometheus-alert.xyz_pod_memory_usage.b011faa
这样可以避免用户接入时因为报警名不符合 DNS-1123 格式而大幅修改自己的报警

**Comment by huangjiuyuan** [comment]
我们目前先通过将 DNS1123 的非法字符替换成 `-` 的方式解决这个问题，本月 Release 的版本和 Helm 部署中将包含修复 #123 。
