### ISSUE TITLE
How to use systemctl in agent pod?

### ISSUE THREAD

**Issue by zqzzq** [kubediag/kubediag#128]
I want to use systemctl cmd to get some info, like ```systemctl status kubelet```, is there some doc about this?

**Comment by huangjiuyuan** [comment]
We had an [implementation](https://github.com/kubediag/kubediag/blob/master/pkg/types/systemd.go#L51) via `systemctl show` command in the early version. Would it be sufficient for your scenario? We could port this feature as an Operation to the next release sooner this month.

**Comment by zqzzq** [comment]
Thanks, I've done this by using ```nsenter``` cmd in Operation, closed this.
